// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'kdp_creator_suite';
  static const String PROJECT_VERSION = '3.0.0';
  static const String IMG_APP_LOGO = 'packages/kdp_creator_suite/assets/images/img_app_logo.svg';
  static const String NO_IMAGE = 'packages/kdp_creator_suite/assets/images/no-image.jpg';
  static const String SAD_FACE = 'packages/kdp_creator_suite/assets/images/sad_face.svg';
  static const String UNLOVEDPRODUCTIONS_LOGO_V5_FORGED_IN_PASSION = 'packages/kdp_creator_suite/assets/images/unlovedproductions_logo_v5_forged_in_passion.png';
}
